// Extracts the handful of icons the game uses from the Iconify JSON packs into a small module,
// so the bundle does not ship thousands of unused icons.
// Gameplay symbols: game-icons.net (CC BY 3.0). Interface icons: Phosphor duotone (MIT).
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const gi = JSON.parse(readFileSync(require.resolve("@iconify-json/game-icons/icons.json"), "utf8"));
const ph = JSON.parse(readFileSync(require.resolve("@iconify-json/ph/icons.json"), "utf8"));

const MAP = {
  // resources + scoring
  wood: ["gi", "wood-pile"],
  metal: ["gi", "metal-bar"],
  energy: ["gi", "power-lightning"],
  dominion: ["gi", "laurel-crown"],
  crown: ["gi", "crown"],
  ap: ["gi", "click"],
  timer: ["gi", "stopwatch"],
  trophy: ["gi", "trophy"],
  skull: ["gi", "skull-crossed-bones"],
  // actions
  claim: ["gi", "flying-flag"],
  build: ["gi", "hammer-nails"],
  attack: ["gi", "crossed-swords"],
  fortify: ["gi", "shield"],
  endturn: ["ph", "skip-forward-duotone"],
  // structures + terrain
  hub: ["gi", "radar-dish"],
  factory: ["gi", "factory"],
  city: ["gi", "modern-city"],
  fortress: ["gi", "castle"],
  chain: ["gi", "linked-rings"],
  forest: ["gi", "pine-tree"],
  mine: ["gi", "mining"],
  energy_field: ["gi", "crystal-shine"],
  city_site: ["gi", "tower-flag"],
  plains: ["ph", "plant-duotone"],
  bot: ["gi", "robot-golem"],
  // interface
  info: ["ph", "info-duotone"],
  help: ["ph", "question-duotone"],
  close: ["ph", "x-duotone"],
  plus: ["ph", "plus-duotone"],
  chat: ["ph", "chat-circle-dots-duotone"],
  sound: ["ph", "speaker-high-duotone"],
  mute: ["ph", "speaker-slash-duotone"],
  swap: ["ph", "arrows-left-right-duotone"],
  check: ["ph", "check-duotone"],
  arrow: ["ph", "arrow-right-duotone"],
  bulb: ["ph", "lightbulb-duotone"],
  book: ["ph", "book-open-duotone"],
  pointer: ["ph", "hand-pointing-duotone"],
  keyboard: ["ph", "keyboard-duotone"],
  copy: ["ph", "copy-duotone"],
  users: ["ph", "users-duotone"],
  eye: ["ph", "eye-duotone"],
  warning: ["ph", "warning-duotone"],
  skip: ["ph", "caret-right-duotone"],
};

const packs = { gi, ph };
const out = {};
for (const [name, [pack, id]] of Object.entries(MAP)) {
  const p = packs[pack];
  const icon = p.icons[id];
  if (!icon) throw new Error(`missing icon ${pack}:${id}`);
  out[name] = { body: icon.body, w: icon.width || p.width || 24, h: icon.height || p.height || 24, src: `${pack}:${id}` };
}
writeFileSync(new URL("../src/ui/iconData.js", import.meta.url), `// GENERATED by scripts/gen-icons.mjs — do not edit by hand.\n// game-icons.net icons are CC BY 3.0 (see credits in the How to Play screen); Phosphor icons are MIT.\nexport const ICONS = ${JSON.stringify(out, null, 1)};\n`);
console.log("wrote", Object.keys(out).length, "icons");
